// socket
export const SET_WEBSOCKET = "SET_WEBSOCKET";
export const SET_SOCKET_CONNECTION = "SET_SOCKET_ON_CONNECTION";
export const UPDATE_IS_CONNECTED = "UPDATE_IS_CONNECTED";
export const UPDATE_ALL_USERS = "UPDATE_ALL_USERS";
export const UPDATE_MESSAGE_TABLE_ON_SEND = "UPDATE_MESSAGE_TABLE_ON_SEND";
export const UPDATE_MESSAGE_TABLE_ON_RECIEVE = "UPDATE_MESSAGE_TABLE_ON_RECIEVE"
export const UPDATE_ALL_MESSAGE = "UPDATE_ALL_MESSAGE";
export const UPDATE_CONNECTED_USERS = "UPDATE_CONNECTED_USERS";

// auth
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const RESET_LOGGED_IN_USER = "RESET_LOGGED_IN_USER";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
export const SET_TOKEN = "SET_TOKEN";

//chat
export const SET_SELECTED_USER = "SET_SELECTED_USER"; 
